name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: asdf-vm/actions/setup@v3
      - name: checkout_plugin
        uses: actions/checkout@v4
        with:
          path: ~/.asdf/plugins/php
      - name: require_php
        run: echo "php" > ~/.tool-versions
      - name: install_php
        run: asdf install php
      - name: test_php
        run: php -v
